
version: "3.9"

services:
  nuxt:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  flask:
    build:
      context: ./backend
    ports:
      - "8000:8000"

