version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-portofolio-nuxt
    environment:
      - MYSQL_ROOT_PASSWORD=portofolio-nuxt
      - MYSQL_DATABASE=portofolio-nuxt_db
      - MYSQL_USER=portofolio-nuxt
      - MYSQL_PASSWORD=portofolio-nuxt
    ports:
      - "3306:3306"   # ou "3307:3306" si conflit
    volumes:
      - mysqldatapn:/var/lib/mysql
    restart: unless-stopped 

  phpmyadmin:                                                             
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-portofolio-nuxt
    environment:
      PMA_HOST: mysql
      PMA_USER: portofolio-nuxt
      PMA_PASSWORD: portofolio-nuxt
    ports:
      - "8080:80"
    depends_on:
      - mysql
  
volumes:
  mysqldatapn:
